version: '3.9'

services:
  app:
    build: .
    command: bash
    tty: true
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  bundle:
  postgresql-data:
